"use client";

import type { NewsItem } from "@/types/news";

// Picsum photos keyed by topic so seeds are visually relevant
const IMG = (seed: number, w = 900, h = 500) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

const seedFeed: NewsItem[] = [
  {
    id: "seed-1",
    source: "rss",
    url: "https://www.theguardian.com",
    title: "UN climate summit reaches historic agreement on fossil fuel phase-out by 2035",
    summary: "Nations representing 80% of global emissions committed to a binding timeline ending coal and gas subsidies, the most ambitious collective pledge in three decades of climate negotiations.",
    category: "climate",
    hypeScore: 94,
    publishedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    imageUrl: IMG(237),
  },
  {
    id: "seed-2",
    source: "arxiv",
    url: "https://arxiv.org",
    title: "Webb telescope detects organic molecules in the atmosphere of a habitable-zone exoplanet",
    summary: "Spectroscopic data shows methane, CO₂, and traces of dimethyl sulphide — a compound only produced by living organisms on Earth — 70 light-years away.",
    category: "science",
    hypeScore: 91,
    publishedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    imageUrl: IMG(1025),
  },
  {
    id: "seed-3",
    source: "rss",
    url: "https://feeds.bbci.co.uk",
    title: "G7 agrees joint framework on AI safety standards and mandatory disclosure rules",
    summary: "The seven nations will align on transparency requirements for frontier AI systems and establish a shared incident-response protocol to handle catastrophic failures.",
    category: "ai",
    hypeScore: 87,
    publishedAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    imageUrl: IMG(180),
  },
  {
    id: "seed-4",
    source: "rss",
    url: "https://feeds.npr.org",
    title: "Alzheimer's trial drug shows 35% reduction in cognitive decline over 18 months",
    summary: "The compound targets amyloid plaques and tau tangles simultaneously — a dual approach that previously failed in separate trials — reigniting hopes for the 50 million people living with dementia.",
    category: "health",
    hypeScore: 85,
    publishedAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    imageUrl: IMG(614),
  },
  {
    id: "seed-5",
    source: "rss",
    url: "https://www.theguardian.com/world",
    title: "Ceasefire agreement collapses in Sudan as rival factions resume fighting near Khartoum",
    summary: "The 72-hour humanitarian pause brokered by the African Union ended without a permanent deal, leaving millions displaced and aid convoys unable to reach the capital.",
    category: "world",
    hypeScore: 83,
    publishedAt: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    imageUrl: IMG(342),
  },
  {
    id: "seed-6",
    source: "rss",
    url: "https://www.technologyreview.com",
    title: "The quiet death of the open-plan office — and what replaces it",
    summary: "Four years of remote-work data show that ambient noise destroys deep focus. Companies are now investing in acoustic pods, asynchronous culture, and radical calendar hygiene.",
    category: "ideas",
    hypeScore: 79,
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    imageUrl: IMG(96),
  },
  {
    id: "seed-7",
    source: "rss",
    url: "https://feeds.arstechnica.com",
    title: "TSMC's 2nm chip enters risk production — here's what it changes",
    summary: "Apple and NVIDIA have reserved the first batches. The gate-all-around transistor architecture delivers 15% performance gains and 30% lower power at the same clock speed.",
    category: "tech",
    hypeScore: 77,
    publishedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    imageUrl: IMG(453),
  },
  {
    id: "seed-8",
    source: "rss",
    url: "https://feeds.npr.org",
    title: "Federal Reserve holds rates steady; signals two cuts possible before year-end",
    summary: "Chair Powell cited softening inflation data but warned that geopolitical disruptions to supply chains could change the picture rapidly.",
    category: "business",
    hypeScore: 74,
    publishedAt: new Date(Date.now() - 1000 * 60 * 165).toISOString(),
    imageUrl: IMG(211),
  },
  {
    id: "seed-9",
    source: "rss",
    url: "https://www.theguardian.com/politics",
    title: "Supreme Court hears landmark case that could redefine digital privacy rights",
    summary: "Justices questioned whether the third-party doctrine — a 40-year-old precedent — can survive in a world where every location, purchase, and conversation is stored in the cloud.",
    category: "politics",
    hypeScore: 72,
    publishedAt: new Date(Date.now() - 1000 * 60 * 195).toISOString(),
    imageUrl: IMG(565),
  },
  {
    id: "seed-10",
    source: "rss",
    url: "https://rss.sciam.com",
    title: "A new study rewrites the timeline of human migration into the Americas",
    summary: "Stone tools discovered in southern Chile date to 23,000 years ago — nearly 8,000 years earlier than the accepted model, suggesting multiple waves of migration by sea.",
    category: "science",
    hypeScore: 70,
    publishedAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    imageUrl: IMG(803),
  },
  {
    id: "seed-11",
    source: "rss",
    url: "https://www.newscientist.com",
    title: "Why we sleep badly when temperatures rise — and what to do about it",
    summary: "Core body temperature must drop 1–2°C for deep sleep to begin. As nights warm, millions are losing an hour of sleep per week without knowing the cause.",
    category: "health",
    hypeScore: 68,
    publishedAt: new Date(Date.now() - 1000 * 60 * 250).toISOString(),
  },
  {
    id: "seed-12",
    source: "rss",
    url: "https://www.technologyreview.com",
    title: "Cannes 2025: the films that matter and why the industry is quietly panicking",
    summary: "Streaming wars, AI-generated scripts, and a divided jury. The world's most prestigious film festival reflects a medium in genuine existential crisis.",
    category: "culture",
    hypeScore: 65,
    publishedAt: new Date(Date.now() - 1000 * 60 * 290).toISOString(),
    imageUrl: IMG(701),
  },
];

export function getInitialFeed(): NewsItem[] {
  return seedFeed;
}
